[package]
name = "k0105/blossom-scripts"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
iris = "xswezan/iris@2.0.5"
promise = "evaera/promise@4.0.0"
fastsignal = "lucasmzreal/fastsignal@10.4.0"
