[package]
name = "realdeedy/fusion"
description = "A fork of Fusion"
license = "MIT"
authors = ["Elttob"]
version = "0.3.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
