return {
    ["Name"] = script.Name,
    ["Date"] = "October 22, 2024",
    ["Title"] = "UPDATE 6 \240\159\142\131",
    ["Image"] = "rbxassetid://104862039221364",
    ["Code"] = nil,
    ["Changes"] = {
        { "Title", "\240\159\142\131 SPOOKY EVENT" },
        { "Description", "COLLECT CANDY - Candy can be earned from completing the new tasks on the Event page!" },
        { "Description", "SPEND CANDY - Spend your Candy on new stuff in the Shop!" },
        { "Description", "CANDY RUSH - FREE x2 Candy boost until you earn 100 Candy! This boost comes back EVERY DAY!" },
        { "Description", "Here for a limited time only!" },
        { "Title", "\240\159\146\128 MAPS" },
        { "Description", "NEW Graveyard map \226\128\148 Battle against your rivals in this spooky new map! Made by @GreatGuyBoom!" },
        { "Description", "REFRESHED Onyx map \226\128\148 Onyx has gotten a permanent visual refresh!" },
        { "Description", "DECORATED Maps \226\128\148 Arena, Big Arena, Shooting Range, Crossroads, Big Crossroads, Construction, Splash, Big Splash, Backrooms, Big Backrooms, Station, & Docks are now a little bit more spooky for a limited time only!" },
        { "Title", "\226\156\168 GAMEMODE" },
        { "Description", "Double Trouble \226\128\148 2v2 duels with a twist - you can use 2 weapons at the same time!" },
        { "Description", "Here for a limited time only!" },
        { "Title", "\226\154\148 REMATCHING" },
        { "Description", "You can now rematch the enemy team after a duel ends!" },
        { "Description", "ALL players must agree to the rematch for it to work!" },
        { "Description", "You can only rematch up to 2 times - make them count!" },
        { "Title", "\240\159\148\165 SHOP" },
        { "Description", "NEW Spooky Skin Case \226\128\148 Contains brand new, limited time spooky skins for all weapons!" },
        { "Description", "NEW Haunted Chest \226\128\148 Contains brand new, limited time spooky wraps, charms, & finishers!" },
        { "Description", "NEW RIP Finisher \226\128\148 Brand new, limited time finisher on sale for Candy!" },
        { "Description", "NEW Hallow Wrap \226\128\148 Brand new, limited time wrap on sale for Candy!" },
        { "Description", "NEW Skull Charm \226\128\148 Brand new, limited time charm on sale for Candy!" },
        { "Description", "You can now gift your friends x3 Skin Cases at once instead of x1!" },
        { "Title", "\240\159\155\146 DAILY SHOP" },
        { "Description", "You can now get a FREE offer from the Daily Shop EVERY DAY!" },
        { "Description", "The Daily Shop now displays up to 5 skins & over 40 wraps, charms, and finishers!" },
        { "Description", "You can now spend Keys to refresh the Daily Shop instantly!" },
        { "Title", "\240\159\147\184 CHARMS" },
        { "Description", "NEW Chex Charm - Eliminate @chexworldwide to earn this brand new charm!" },
        { "Description", "NEW Hoopie Charm - Eliminate @EHoopie to earn this brand new charm!" },
        { "Description", "NEW hoppy819 Charm - Eliminate @h0ppy819 to earn this brand new charm!" },
        { "Title", "\240\159\148\171 BALANCE CHANGES" },
        { "Header", "Minigun" },
        { "Description", "\240\159\147\157 \"The Minigun was tuned to a stronger state than expected\"" },
        { "Description", "\240\159\148\187 Damage decreased from 9 \226\134\146 8" },
        { "Header", "Paintball Gun" },
        { "Description", "\240\159\147\157 \"Playing against the new paintball splats proved to be frustrating\"" },
        { "Description", "\240\159\148\187 Getting shot by a paintball no longer obscures the player that shot you" },
        { "Header", "RPG" },
        { "Description", "\240\159\147\157 \"Keeping some kind of strong direct hit damage requires a weaker splash damage\"" },
        { "Description", "\240\159\148\187 Direct hit damage decreased from 150 \226\134\146 120" },
        { "Description", "\240\159\148\187 Splash damage decreased from 50 \226\134\146 40" },
        { "Header", "Shotgun" },
        { "Description", "\240\159\147\157 \"We\'re enabling more dynamic gameplay for the Shotgun and providing a more consistent spread\"" },
        { "Description", "\240\159\146\170 Move speed increased from -10% \226\134\146 Normal" },
        { "Description", "\226\158\150 Pellet count increased from 6 \226\134\146 10" },
        { "Header", "Exogun" },
        { "Description", "\240\159\147\157 \"The Exogun was too strong for a secondary\"" },
        { "Description", "\240\159\148\187 Direct hit damage decreased from 28 \226\134\146 20" },
        { "Description", "\240\159\146\170 Splash damage increased from 6 \226\134\146 10" },
        { "Header", "Handgun" },
        { "Description", "\240\159\147\157 \"We\'re helping the Handgun compete with other secondaries\"" },
        { "Description", "\240\159\146\170 Damage increased from 10 \226\134\146 11" },
        { "Header", "Revolver" },
        { "Description", "\240\159\147\157 \"We\'re reverting the Revolver\'s damage to be better aligned with other secondaries\"" },
        { "Description", "\240\159\148\187 Damage reduced from 34 \226\134\146 33" },
        { "Header", "Uzi" },
        { "Description", "\240\159\147\157 \"The damage dropoff and spread changes reduced Uzi\'s power more than expected\"" },
        { "Description", "\240\159\146\170 Damage increased from 7 \226\134\146 8" },
        { "Description", "\240\159\146\170 Spread while aiming decreased from 3\194\176 \226\134\146 0\194\176" },
        { "Title", "\240\159\155\160 OTHER" },
        { "Description", "Daily Tasks have been changed & now give more keys!" },
        { "Description", "Onyx has been added back to the 2v2v2 queue!" },
        { "Description", "NEW ADS Sensitivity Multiplier Setting \226\128\148 Allows you to have a different sensitivity while aiming with a gun!" },
        { "Description", "NEW Finisher Volume Setting \226\128\148 Allows you to mute finishers!" },
        { "Description", "Performance improvements for Team Deathmatch & Free For All gamemodes!" },
        { "Description", "The Tasks button at the bottom of your screen now quickly shows you how many daily tasks are completed at a quick glance!" },
        { "Description", "New icon for the Torch Molotov skin!" },
        { "Description", "New icon for the Flamethrower!" },
        { "Description", "Sounds for the Collapse finisher have been slightly changed!" },
        { "Description", "New UI for viewing lootbox contents!" },
        { "Description", "The Pixel Flamethrower now has new particles when setting an enemy on fire!" },
        { "Title", "\240\159\144\155 BUG FIXES" },
        { "Description", "Potentially fixed a bug with replication that caused several other bugs such as invisible weapons, floating weapons, overlapping UI, missing players from the team UI, missing/duplicate players in the scoreboard, etc." },
        { "Description", "Fixed a bug with Freeze Ray where it wouldn\'t count towards assists/eliminations" },
        { "Description", "Fixed a bug with Freeze Ray where freezes wouldn\'t count towards the total freezes statistic" },
        { "Description", "Fixed a bug that allowed you to disable paint splatters from the Paintball Gun by turning your HUD off" },
        { "Description", "Fixed a bug that allowed players to see through the countdown screen for matchmade duels" },
        { "Description", "Fixed a bug with the blimps in Construction that caused them to disappear" },
        { "Description", "Fixed a visual bug with the Blobsaw skin where the spikes wouldn\'t move and there were no particles when using your ability" },
        { "Description", "Fixed a bug where sometimes picking your weapons wouldn\'t work" },
        { "Description", "Fixed a bug with tightropes that made aiming down sights not work properly" },
        { "Description", "Fixed a bug that allowed you to go inbetween train carts by the tunnel in Station" },
        { "Description", "Fixed a bug that allowed you to hide in the ceiling in the Big Crossroads mountain" },
        { "Description", "Fixed a bug with the Disabled Textures setting that wouldn\'t disable textures from the Lobby" },
        { "Title", "\240\159\147\156 A NOTE FROM THE DEVELOPERS" },
        { "Description", "Hope you all enjoy the update!!" }
    }
}