return {
    ["Name"] = script.Name,
    ["Date"] = "August 2, 2024",
    ["Title"] = "UPDATE 3 \240\159\148\165",
    ["Image"] = "rbxassetid://18769680466",
    ["Code"] = nil,
    ["Changes"] = {
        { "Title", "\240\159\148\165 NEW SKIN CASE 2!" },
        { "Description", "A BRAND NEW SKIN CASE IS HERE!" },
        { "Description", "Contains brand new skins for all current weapons in the game!" },
        { "Description", "Skins for Revolver, Handgun, Assault Rifle, & Medkit COMING SOON!" },
        { "Description", "Now available in the Shop!" },
        { "Title", "\240\159\147\166 NEW WRAP BOX 2!" },
        { "Description", "A BRAND NEW WRAP BOX IS HERE!" },
        { "Description", "Contains brand new wraps which can be applied to ANY weapon & skin!" },
        { "Description", "Now available in the Shop!" },
        { "Title", "\240\159\155\146 NEW SHOP ITEMS" },
        { "Description", "The Beach Wrap is now available to purchase in the Shop for a limited time only!" },
        { "Description", "The Watermelon Wrap is now available to purchase in the Shop for a limited time only!" },
        { "Description", "The Groove Wrap is no longer available in the Shop!" },
        { "Description", "The RPKEY RPG in the Legendary Key Bundle has been replaced with the brand new Keythe Scythe skin!" },
        { "Title", "\240\159\142\129 GIFTING!" },
        { "Description", "Gifting is finally here!" },
        { "Description", "You can now gift bundles, gamepasses, skin cases, & more to your friends!" },
        { "Description", "Visit the Shop and press the pink gift icon to get started!" },
        { "Title", "\226\154\148\239\184\143 DUEL HISTORY!" },
        { "Description", "You can now view your duel history!" },
        { "Description", "Your duel history will show who you recently dueled, the exact stats of everyone in the duel, the map you played on, & more!" },
        { "Description", "Head over to the Career page to get started!" },
        { "Title", "\240\159\148\171 BALANCE CHANGES" },
        { "Description", "\240\159\148\187 Paintball Gun damage decreased from 19 \226\134\146 18" },
        { "Description", "\240\159\146\170 Fists damage increased from 25 \226\134\146 30" },
        { "Description", "\240\159\146\170 Handgun damage increased from 12 \226\134\146 13" },
        { "Description", "\240\159\148\187 Exogun damage decreased from 28 \226\134\146 25" },
        { "Description", "\240\159\146\170 Shotgun total damage increased from 60 \226\134\146 75" },
        { "Description", "\240\159\146\170 Shorty total damage increased from 60 \226\134\146 75" },
        { "Description", "\240\159\146\170 Trowel damage increased from 40 \226\134\146 45" },
        { "Description", "\240\159\148\187 Slingshot ammo decreased from 100 \226\134\146 75" },
        { "Description", "\240\159\146\170 Grenade Launcher damage increased from 45 \226\134\146 49" },
        { "Title", "\240\159\155\160 OTHER" },
        { "Description", "Map voting now only shows 3 random options to prevent abuse" },
        { "Description", "Flare Gun Eliminations contract changed to Damage Dealt" },
        { "Description", "Grenade Eliminations contract changed to Damage Dealt" },
        { "Description", "Molotov Eliminations contract changed to Damage Dealt" },
        { "Description", "Subspace Tripmine Eliminations contract changed to Damage Dealt" },
        { "Description", "Freeze Ray Freezes contract goal increased" },
        { "Description", "Flash Bang Blinds contract goal increased" },
        { "Description", "Temporal Ray skin rarity changed from Rare to Legendary" },
        { "Description", "Goalpost Slingshot skin has been moved from Skin Case to Skin Case 2" },
        { "Description", "If you receive a skin you already own, it will now go into your Backpack (ex: from Legendary Key Bundles). Players that previously purchased multiple Legendary Key Bundles should now have bonus RPKEYs in their Backpack!" },
        { "Title", "\240\159\144\155 BUG FIXES" },
        { "Description", "Fixed a bug where hit % and critical hit % statistics failed to calculate" },
        { "Description", "Fixed a bug where quick attacks were not being tracked in statistics" },
        { "Description", "Fixed a bug where ultrawide monitor players were blinded by paintball splatters" },
        { "Description", "Fixed a bug where certain avatar hats with particles would obstruct vision" },
        { "Title", "\240\159\147\156 A NOTE FROM THE DEVELOPERS" },
        { "Description", "We apologize for the 2 hour delay on the update, please use code SORRY for x10 Keys & x1 Wrap Box 2 (only available for the next 24 hours)" },
        { "Description", "Region-based & skill-based matchmaking are still currently in the works! This will greatly improve the experience of matchmade games and pave the way for Ranked to come out. Thank you for being patient as we actively work on it!" },
        { "Description", "In the meantime, we will be working on some exciting new gameplay updates. Stay tuned for more information..." }
    }
}