return {
    ["Name"] = script.Name,
    ["Date"] = "July 12, 2024",
    ["Title"] = "UPDATE 1 \226\157\132",
    ["Image"] = "rbxassetid://18431450301",
    ["Code"] = nil,
    ["Changes"] = {
        { "Title", "\226\156\168 NEW WEAPON - Freeze Ray!" },
        { "Description", "This powerful new Standard Utility is able to freeze multiple enemies at once!" },
        { "Description", "Complete Freeze Ray contracts to unlock the brand new Cool & Crossed wraps!" },
        { "Description", "New Temporal Ray skin for the Freeze Ray! Can be unboxed from the Skin Case!" },
        { "Description", "Early Access available to Standard Weapons Gamepass owners!" },
        { "Description", "Full weapon release in 24 hours!" },
        { "Title", "\240\159\140\142 NEW MAP - Big Arena!" },
        { "Description", "Experience the iconic Arena map with way more duelers!" },
        { "Description", "Only available for 3v3s and up!" },
        { "Title", "\240\159\142\168 NEW WRAP - Experience!" },
        { "Description", "Obtained every 10 career levels for free!" },
        { "Title", "\226\154\153 NEW SETTINGS" },
        { "Description", "Damage Numbers - Allows you to see the exact amount of damage you deal to other duelers!" },
        { "Description", "Crosshair Bars Shape - Allows you to change the shape of the crosshair\'s bars!" },
        { "Description", "Crosshair Dot Shape - Allows you to change the shape of the crosshair\'s dot!" },
        { "Description", "Scroll Equip - Allows you to turn off the scroll equip mechanic for Mouse & Keyboard controls!" },
        { "Description", "Double Tap To Shoot - Allows you to turn off the double tap to shoot mechanic for Touch controls!" },
        { "Title", "\240\159\148\171 BALANCE CHANGES" },
        { "Description", "\240\159\146\170 Sniper body shot damage has been increased from 50 \226\134\146 70" },
        { "Description", "\240\159\146\170 Sniper ammo reserve has been increased from 5 \226\134\146 10" },
        { "Description", "\240\159\148\187 Exogun ammo has been decreased from 10 \226\134\146 6" },
        { "Description", "\240\159\148\187 Exogun ammo reserve has been decreased from 50 \226\134\146 28" },
        { "Description", "\240\159\146\170 Shotgun now has a predictable spread pattern" },
        { "Description", "\226\158\150 Shotgun pellet count has been increased from 5 \226\134\146 6" },
        { "Description", "\240\159\148\187 Shotgun damage has been decreased from 75 \226\134\146 60" },
        { "Description", "\240\159\146\170 Shorty now has a predictable spread pattern" },
        { "Description", "\240\159\148\187 Shorty damage has been decreased from 80 \226\134\146 60" },
        { "Title", "\240\159\155\160 OTHER" },
        { "Description", "Getting an assist from a player that was eliminated by the environment now counts as an elimination! For example, enemies that fall off the map after you blind them will now give you an elimination instead of an assist!" },
        { "Description", "Smoke Grenade \"Assists\" contract has been changed to \"Enemies Smoked\"" },
        { "Description", "Flashbang \"Assists\" contract has been changed to \"Enemies Blinded\"" },
        { "Description", "Ending a dueler\'s 100+ win streak will now broadcast your accomplishment to all servers worldwide!" },
        { "Description", "Equip weapon buttons on mobile can now be customized!" },
        { "Description", "Private Servers now have a 3-team-infinite-players duel pad!" },
        { "Description", "Private Servers now let you vote for any map!" },
        { "Description", "Footsteps & climbing sounds can now be heard from farther away!" },
        { "Description", "Your health bar now displays exactly how much health you have left!" },
        { "Description", "Improved keybind visuals & hotkey settings page!" },
        { "Description", "Invalid wins from rage quitters should now happen less often!" },
        { "Description", "Dozens of bug fixes & quality of life improvements!" }
    }
}