return {
    ["Name"] = script.Name,
    ["Date"] = "May 30, 2025",
    ["Title"] = "UPDATE 13 \240\159\146\165",
    ["Image"] = "rbxassetid://137451307320521",
    ["Code"] = "patchnotes_gamemodes2",
    ["Changes"] = {
        { "Title", "\240\159\142\130 1st BIRTHDAY" },
        { "Description", "It\'s RIVALS\' first ever birthday \226\128\148 the game was released on June 28, 2024!" },
        { "Description", "Thank you all for playing RIVALS, it\'s been an incredible year and we\'re super excited to keep pushing RIVALS to be the best FPS game ever on Roblox!" },
        { "Description", "To celebrate, we\'ve thrown a birthday party in the hub! There\'s also 2 new wraps that can be purchased in the Shop \226\128\148 only available during birthday parties!" },
        { "Title", "\240\159\146\165 ROTATING QUEUES" },
        { "Description", "The brand new, rotating gamemode queues are here!" },
        { "Description", "From now on, experience a brand new gamemode every week in the Play page!" },
        { "Description", "Brand new gamemodes will be releasing WEEKLY for the rest of the summer, starting with Juggernaut!" },
        { "Title", "\240\159\149\185 ARCADE SERVER" },
        { "Description", "There\'s been a lot of changes made to the traditional gamemodes \226\128\148 Team Deathmatch & Free For All!" },
        { "Description", "To start off, both of these gamemodes have been merged into 1 place \226\128\148 the Arcade Server!" },
        { "Description", "Games in the Arcade Server will now alternate between all available gamemodes one after another!" },
        { "Description", "To keep the gameplay fresh, we\'ve limited the number of votable maps in the Arcade Server to 3. However, we also made it so that the map with the most votes will *always* win!" },
        { "Description", "Gamemodes inside of the Arcade Server have also been given Health & Ammo Drops! After eliminating a player, they\'ll drop Health & Ammo which you can use to replenish your losses and continue battling!" },
        { "Description", "You can now also quickly respawn in the Arcade Server. Simply press your Jump keybind or tap the Respawn button!" },
        { "Description", "We also understand that many of you prefer playing these gamemodes over classic duels, which is why Daily Tasks & Bonus Tasks can now also be completed in the Arcade Server!" },
        { "Title", "\226\154\148 TEAM DEATHMATCH" },
        { "Description", "Team Deathmatch has been completely changed!" },
        { "Description", "Instead of players competing against their own teammates for the individual win, entire teams can now win the game!" },
        { "Description", "Eliminating an enemy player now increases your team\'s score. Once your team reaches 250 points, everyone on your team wins!" },
        { "Description", "You may now also switch teams while playing Team Deathmatch, so long as the enemy team isn\'t too big!" },
        { "Description", "Play now in the Arcade Server!" },
        { "Title", "\240\159\142\175 GUN GAME" },
        { "Description", "A brand new gamemode is here in the Arcade Server \226\128\148 Gun Game!" },
        { "Description", "Race through a random sequence of weapons to be the first to eliminate a player with the Glast Shard!" },
        { "Description", "You don\'t need to have any weapons unlocked to enjoy this gamemode \226\128\148 experience RIVALS\' entire arsenal of weapons for free!" },
        { "Description", "Gun Game supports up to 16 players, has Health & Ammo Drops, supports completing your Daily Tasks & Bonus Tasks, and contains all of the other great things the Arcade Server has to offer!" },
        { "Description", "Play now in the Arcade Server!" },
        { "Title", "\240\159\155\161 PRIVATE SERVERS" },
        { "Description", "We want Private Servers to be a place where all players can play the game for fun with their friends. With that being said, here are the amazing new things we\'ve added to Private Servers!" },
        { "Description", "You can now use locked weapons while in a Private Server! This feature can be turned off by the Private Server owner." },
        { "Description", "Private Server owners can now change a bunch of settings for the queue pads! You can now change the duel mode, number of players, turn on unlimited time, and more!" },
        { "Description", "Every single old & upcoming gamemode is now available to play in Private Servers!" },
        { "Description", "Gun Game is now available to play in Private Servers, too!" },
        { "Description", "By the way.. Private Servers are completely FREE! No strings attached!" },
        { "Title", "\240\159\142\128 SKINS" },
        { "Description", "There\'s 11 new skins added to the Skin Case 3!" },
        { "Description", "NEW Legendary Spray Bottle skin for the Spray!" },
        { "Description", "NEW Legendary Void Rifle skin for the Energy Rifle!" },
        { "Description", "NEW Legendary Gunsaw skin for the Gunblade!" },
        { "Description", "NEW Rare Cerulean Axe skin for the Battle Axe!" },
        { "Description", "NEW Rare Air Horn skin for the Warhorn!" },
        { "Description", "NEW Rare Masterpiece skin for the Riot Shield!" },
        { "Description", "NEW Rare Hydro Pistols skin for the Energy Pistols!" },
        { "Description", "NEW Rare Shady Chicken Sandwich skin for the Jump Pad!" },
        { "Description", "NEW Rare Violin Crossbow skin for the Crossbow!" },
        { "Description", "NEW Common Bag o\' Money skin for the Satchel!" },
        { "Description", "NEW Common Shurikens skin for the Daggers!" },
        { "Description", "All of these skins are now available in Skin Case 3!" },
        { "Title", "\240\159\151\157\239\184\143 KEY BUNDLES" },
        { "Description", "The Legendary Key Bundle now contains the brand new Mythical Shotkey skin for the Shotgun!" },
        { "Description", "The Ultra Key Bundle now contains the brand new Mythical Keyzi skin for the Uzi!" },
        { "Title", "\240\159\148\171 BALANCE CHANGES" },
        { "Header", "Burst Rifle" },
        { "Description", "\240\159\147\157 \"The Burst Rifle\'s sustain damage is too strong for its intended playstyle\"" },
        { "Description", "\240\159\148\187 Cooldown increased from 0.5s \226\134\146 0.6s" },
        { "Description", "\240\159\148\187 Max Ammo decreased from 21 \226\134\146 15" },
        { "Description", "\240\159\148\187 Max Ammo Reserve decreased from 63 \226\134\146 60" },
        { "Header", "Energy Rifle" },
        { "Description", "\240\159\147\157 \"The Energy Rifle continues to lack in performance\"" },
        { "Description", "\240\159\146\170 Bounce Redirection Angle increased from 10\194\176 \226\134\146 15\194\176" },
        { "Header", "Grenade Launcher" },
        { "Description", "\240\159\147\157 \"We want the Grenade Launcher to compete with the RPG and to make juggling easier\"" },
        { "Description", "\240\159\146\170 Projectile speed increased from 75studs/s \226\134\146 90studs/s\194\176" },
        { "Header", "Slingshot" },
        { "Description", "\240\159\147\157 \"The Slingshot\'s large hitboxes are frustrating to play against\"" },
        { "Description", "\240\159\148\187 Projectile hitbox size decreased from 5studs \226\134\146 2.5studs" },
        { "Description", "\240\159\146\170 Critical hit multiplier increased from 1.0x \226\134\146 1.25x" },
        { "Header", "Spray" },
        { "Description", "\240\159\147\157 \"The Spray should feel much quicker without affecting its DPS\"" },
        { "Description", "\240\159\146\170 Cooldown decreased from 0.6s \226\134\146 0.4s" },
        { "Description", "\240\159\148\187 Damage decreased from 8 \226\134\146 6" },
        { "Header", "Jump Pad" },
        { "Description", "\240\159\147\157 \"The Jump Pad proved to be too weak on release\"" },
        { "Description", "\240\159\146\170 Max Ammo increased from 1 \226\134\146 2" },
        { "Description", "\240\159\146\170 Launch velocity increased by 20%" },
        { "Title", "\240\159\155\160 OTHER" },
        { "Description", "You can now rematch after a duel ends if you play through matchmaking" },
        { "Description", "Big Onyx has been added to the 1v1v1 and 2v2v2 map pools" },
        { "Description", "Splash now has a smaller playable area" },
        { "Description", "High ELO ranked duels no longer support rematching to prevent abuse" },
        { "Description", "Hiding your HUD will no longer hide the map voting screen" },
        { "Description", "You can now see all of your recent notifications in the new Inbox page" },
        { "Description", "Dozens of quality-of-life additions & fixes for controller players" },
        { "Description", "You can now speak to the NPCs in the lobby" },
        { "Description", "Improved top bar & queue UI" },
        { "Title", "\240\159\144\155 BUG FIXES" },
        { "Description", "Fixed a bug with Trowel that allowed players to fling themselves really fast" },
        { "Description", "Fixed a bug where mobile players were able to perform a mini double jump after slide jumping" },
        { "Description", "Fixed a bug where animations wouldn\'t play properly when spectating a player using the Gunblade" },
        { "Description", "Fixed a bug where the mobile aim button stayed on after shooting with the Sniper and Crossbow, as well as reloading while aiming & shooting with most guns" },
        { "Description", "Projectile weapons such as Bow & Daggers should now have much more reliable hitboxes" },
        { "Description", "Fixed a bug where player nametags would incorrectly show up during a duel" },
        { "Description", "Fixed a bug in Crossroads & Big Crossroads where players could stand on top of the invisible walls" },
        { "Description", "Fixed a bug in Station where players could fall through the train tracks" },
        { "Description", "Fixed a few spawns in Station that would make you fall through the map" },
        { "Description", "Fixed a bug where sliding into a train cart in Station would eliminate you" },
        { "Description", "Fixed a bug where you could hide under the water in Splash & Big Splash" },
        { "Description", "Fixed a bug where you could hide under the map in Graveyard & Big Graveyard" },
        { "Description", "Fixed a bug in all maps where players were able to stand on top of invisible parts" },
        { "Description", "Fixed a bug where the crosshair UI wasn\'t centered on some mobile devices" },
        { "Description", "Fixed a rare bug where the Subspace Tripmine could cause players to be flung into the void" },
        { "Description", "Fixed a visual bug when wrapping the Megaphone skin" },
        { "Description", "Fixed a bug where high ELO players in Ranked would incorrectly receive dodge penalties when their teammates wouldn\'t connect" },
        { "Description", "Fixed a bug where there could be more than 200 Archnemesis players if players either were tied with #200 or were leaderboard banned and had enough ELO to be in the top 200" },
        { "Description", "Fixed a bug where Ranked players in Platinum 1 and Platinum 2 would still receive Daily ELO Shields" }
    }
}